import { NextResponse } from "next/server";
import { z } from "zod";
import { requireOnboardedUser } from "@/lib/auth/guards";
import { createAdminRecord, escapeFilter, findAdminRecord, listAdminRecords, updateAdminRecord } from "@/lib/pocketbase/records";
import type { PocketBaseRecord } from "@/lib/pocketbase/types";
import type { MatchRecord } from "@/lib/repositories/matches";
import type { ComplimentRecord } from "@/lib/repositories/compliments";
const schema=z.object({blockedUserId:z.string().min(1),reason:z.string().max(500).optional()});
export async function POST(request:Request){const user=await requireOnboardedUser();const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success||parsed.data.blockedUserId===user.id)return NextResponse.json({message:"Invalid block."},{status:400});const pair=`blocker="${escapeFilter(user.id)}" && blocked="${escapeFilter(parsed.data.blockedUserId)}"`;if(!(await findAdminRecord<PocketBaseRecord>("blocks",pair)))await createAdminRecord("blocks",JSON.stringify({blocker:user.id,blocked:parsed.data.blockedUserId,reason:parsed.data.reason||""}));const matches=await listAdminRecords<MatchRecord>("matches",new URLSearchParams({page:"1",perPage:"50",filter:`status="active" && ((participant_one="${user.id}" && participant_two="${parsed.data.blockedUserId}") || (participant_one="${parsed.data.blockedUserId}" && participant_two="${user.id}"))`}));const compliments=await listAdminRecords<ComplimentRecord>("compliments",new URLSearchParams({page:"1",perPage:"100",filter:`status="pending" && ((sender="${user.id}" && recipient="${parsed.data.blockedUserId}") || (sender="${parsed.data.blockedUserId}" && recipient="${user.id}"))`}));await Promise.all([...matches.items.map((match)=>updateAdminRecord("matches",match.id,JSON.stringify({status:"blocked",ended_by:user.id,end_reason:"blocked",ended_at:new Date().toISOString()}))),...compliments.items.map((compliment)=>updateAdminRecord("compliments",compliment.id,JSON.stringify({status:"ignored",decided_at:new Date().toISOString()})))]);return NextResponse.json({ok:true});}
