import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth/guards";
import { createAdminRecord, escapeFilter, findAdminRecord, updateAdminRecord } from "@/lib/pocketbase/records";
import type { AuthRecord } from "@/lib/pocketbase/types";
import type { ProfileRecord } from "@/lib/repositories/profiles";
import { buildModerationAudit } from "@/lib/services/moderation";
const schema=z.object({action:z.enum(["suspend","unsuspend","hide_profile","restore_profile","close_account","correct_birth_date"]),reason:z.string().trim().min(3).max(2000),birthDate:z.string().optional()});
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){const admin=await requireAdmin();const{id}=await params;const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({message:"Invalid moderation action."},{status:400});const user=await findAdminRecord<AuthRecord>("users",`id="${escapeFilter(id)}"`);if(!user)return NextResponse.json({message:"User not found."},{status:404});const profile=await findAdminRecord<ProfileRecord>("profiles",`user="${escapeFilter(id)}"`);const before={accountState:user.account_state,birthDate:user.birth_date,profileVisible:profile?.moderation_visible};const after={...before};if(parsed.data.action==="suspend"){await updateAdminRecord("users",id,JSON.stringify({account_state:"suspended",suspension_reason:parsed.data.reason}));after.accountState="suspended";}if(parsed.data.action==="unsuspend"){await updateAdminRecord("users",id,JSON.stringify({account_state:"active",suspension_reason:""}));after.accountState="active";}if(parsed.data.action==="close_account"){await updateAdminRecord("users",id,JSON.stringify({account_state:"deactivated"}));after.accountState="deactivated";}if((parsed.data.action==="hide_profile"||parsed.data.action==="restore_profile")&&profile){const visible=parsed.data.action==="restore_profile";await updateAdminRecord("profiles",profile.id,JSON.stringify({moderation_visible:visible}));after.profileVisible=visible;}if(parsed.data.action==="correct_birth_date"&&parsed.data.birthDate){await updateAdminRecord("users",id,JSON.stringify({birth_date:parsed.data.birthDate}));after.birthDate=parsed.data.birthDate;}await createAdminRecord("moderation_actions",JSON.stringify(buildModerationAudit({administratorId:admin.id,targetUserId:id,action:parsed.data.action,reason:parsed.data.reason,beforeState:before,afterState:after})));return NextResponse.json({ok:true});}
