import { NextResponse } from "next/server";
import { requireOnboardedUser } from "@/lib/auth/guards";
import { createAdminRecord, escapeFilter, findAdminRecord, listAdminRecords } from "@/lib/pocketbase/records";
import type { MatchRecord } from "@/lib/repositories/matches";
import type { MessageRecord, TypingRecord } from "@/lib/repositories/messages";
import { canSendMessage } from "@/lib/services/chat";

async function context(userId: string, id: string) { const match = await findAdminRecord<MatchRecord>("matches", `id="${escapeFilter(id)}"`); if (!match || (match.participant_one !== userId && match.participant_two !== userId)) return null; return match; }
export async function GET(_request: Request, { params }: { params: Promise<{ id: string }> }) { const user = await requireOnboardedUser(); const { id } = await params; if (!(await context(user.id,id))) return NextResponse.json({ message: "Match not found." }, { status: 404 }); const [messages,typing] = await Promise.all([listAdminRecords<MessageRecord>("messages",new URLSearchParams({page:"1",perPage:"200",sort:"created",filter:`match="${id}" && hidden_at=""`})),listAdminRecords<TypingRecord>("typing_states",new URLSearchParams({page:"1",perPage:"20",filter:`match="${id}" && user!="${user.id}" && expires_at>="${new Date().toISOString()}"`}))]); return NextResponse.json({ messages: messages.items, typing: typing.items.length > 0 }); }
export async function POST(request: Request, { params }: { params: Promise<{ id: string }> }) { const user = await requireOnboardedUser(); const { id } = await params; const match = await context(user.id,id); if (!match) return NextResponse.json({ message: "Match not found." }, { status: 404 }); const body = String((await request.json().catch(() => ({}))).body || ""); const policy = canSendMessage(user.id,{participantOneId:match.participant_one,participantTwoId:match.participant_two,status:match.status},body); if (!policy.success) return NextResponse.json({message:policy.message},{status:400}); const message = await createAdminRecord<MessageRecord>("messages",JSON.stringify({match:id,sender:user.id,body:policy.body})); return NextResponse.json({message},{status:201}); }
